apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-application
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Example Application Project
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
