apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '4'
  labels:
    gitops.ownedBy: cluster-config
  name: prod-example-applicatoin-kustomize
spec:
  destination:
    namespace: dinosaurs-prod
    server: https://kubernetes.default.svc
  project: example-application
  source:
    path: kustomize/overlays/prod
    repoURL: https://github.com/tosmi-gitops/example-application.git
    targetRevision: main
  syncPolicy:
    # automated:
    #   selfHeal: true
