kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
    argocd.argoproj.io/sync-wave: "0"

namespace: goldfish-bookstore

resources:
  - namespace.yaml
  - https://github.com/tosmi-gitops/onboarding-base/overlays/small?ref=v0.0.7
